DROP DATABASE IF EXISTS ESTOQUE;

CREATE DATABASE  ESTOQUE;

USE  ESTOQUE;

CREATE TABLE USUARIO
(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    LOGIN VARCHAR(30) NOT NULL,
    SENHA VARCHAR (30) NOT NULL
);
	
CREATE TABLE PRODUTOS(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME VARCHAR (50) NOT NULL,
DESCRICAO VARCHAR (50) NOT NULL,
PRECO DECIMAL (10,2) NOT NULL,
USUARIO_ID INTEGER
);

CREATE TABLE ADM
(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    LOGIN VARCHAR(30) NOT NULL,
    SENHA VARCHAR (30) NOT NULL
);


